# Generated by Django 6.0.2 on 2026-09-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Feature Title')),
                ('badge', models.CharField(default='ANNOUNCEMENT', max_length=50, verbose_name='Badge Tag')),
                ('description', models.TextField(verbose_name='Feature Description')),
                ('link', models.URLField(blank=True, default='', verbose_name='External Link / URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_or_id', models.CharField(max_length=150, verbose_name='Name or User ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Contact Phone')),
                ('subject', models.CharField(max_length=200, verbose_name='Complaint Subject')),
                ('description', models.TextField(verbose_name='Detailed Grievance')),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/', verbose_name='Attached Photo')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_PROGRESS', 'Under Investigation'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Admin Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Festival Name')),
                ('date_text', models.CharField(max_length=100, verbose_name='Festival Date / Month')),
                ('description', models.TextField(verbose_name='Details & Significance')),
                ('image', models.ImageField(blank=True, null=True, upload_to='festivals/', verbose_name='Festival Poster')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title / Caption')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Photo File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Sponsor Full Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Sent (₹)')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='sponsor_receipts/', verbose_name='Payment Screenshot')),
                ('message', models.CharField(blank=True, default='', max_length=250, verbose_name='Purpose / Message')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Verified Receipt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profile Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenure',
            field=models.CharField(default='2026 - 2032 (6 Years Official Term)', max_length=100, verbose_name='Membership Tenure'),
        ),
    ]
